#include <stdio.h>
#include <stdlib.h>
#include <sstream>
#include <iostream>
#include <string.h>
#include <cstdlib>
#include <ctime>
#include <math.h>
#include "../include/mtrx_funcs.h"
#include "../include/utils.h"
#include <string>